// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWpamrkgOfnPJ_OUBMAxPwB4gcXe2WQsU',
    appId: '1:176999940287:web:fe7f249c3fca9c7284460a',
    messagingSenderId: '176999940287',
    projectId: 'flutterfinal-faffd',
    authDomain: 'flutterfinal-faffd.firebaseapp.com',
    storageBucket: 'flutterfinal-faffd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmdGCH2GRROd99zQyv5Bj9QHQtNYLnHzg',
    appId: '1:176999940287:android:73b0041e7705b70984460a',
    messagingSenderId: '176999940287',
    projectId: 'flutterfinal-faffd',
    storageBucket: 'flutterfinal-faffd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa3GQ4CcNIel_V1E0NV7mNWhGV2cQqMLQ',
    appId: '1:176999940287:ios:46e8b786deb18bab84460a',
    messagingSenderId: '176999940287',
    projectId: 'flutterfinal-faffd',
    storageBucket: 'flutterfinal-faffd.appspot.com',
    iosBundleId: 'com.example.flutterFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa3GQ4CcNIel_V1E0NV7mNWhGV2cQqMLQ',
    appId: '1:176999940287:ios:db24a66b98b9245684460a',
    messagingSenderId: '176999940287',
    projectId: 'flutterfinal-faffd',
    storageBucket: 'flutterfinal-faffd.appspot.com',
    iosBundleId: 'com.example.flutterFinal.RunnerTests',
  );
}
